### ISSUE TITLE
是否有安装文档?

### ISSUE THREAD

**Issue by mandarenmanman** [wikift/wikift#45]
RT

**Comment by qianmoQ** [comment]
安装文档正在补充中，预计这周上线，谢谢您的支持

**Comment by qianmoQ** [comment]
@mandarenmanman deploy document please visit http://wiki.ttxit.com/pages/viewpage.action?pageId=11142808

**Comment by mandarenmanman** [comment]
3q

**Comment by ruke** [comment]
一定在docket环境下面安装吗

**Comment by qianmoQ** [comment]
@ruke 也支持在非docker环境下部署
