### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by lizhuangs** [wikift/wikift#60]
因为我之前也一直在找一款简洁好用的wiki知识管理系统。我心目中完美的wiki有几下基本几点：
1、搜索，可以全文检索并高亮，包括作者，标题，内容和附件名等
2、可以复制粘贴word里面的内容，并且自动分级创建标题目录，很多老的文档或者其它地方复制到一个新wiki里面，这一点是很重要的。标题目录也是很重要的一个东西，它可以直接定位到当前文章的每一条。
3、历史修改记录。wiki是用于共享的，很多人可以修改，但是如果有人改错了，或者删除了，可以列出这个文档最近比如100条记录或者一年以内的记录。
4、如果能做到所见即所得的编辑模式就很好了。支持markdown估计也是很多人期待的。完美的应该是markdown+所见即所得，支持切换到传统的富文档+所见即所得。
其它诸如简单的权限用户管理，文章编辑这里就不细说了。开发这些功能并不能一蹴而就，需要很多时间心血，先star关注中，顺便提点建议，作者可以考虑一下~

**Comment by qianmoQ** [comment]
Thank you for your advice.

please you split this issues to multiple issues.
