### ISSUE TITLE
1.1.0版本可以非docker部署吗？

### ISSUE THREAD

**Issue by xwinfo** [wikift/wikift#68]
如题。

**Comment by qianmoQ** [comment]
有非 docker 的部署方案

**Comment by xwinfo** [comment]
http://wiki.ttxit.com/pages/viewpage.action?pageId=11142808
这个文档是1.0.0的，1.1.0版本的有链接吗

**Comment by qianmoQ** [comment]
1.1.0 的文档还在补

**Comment by xwinfo** [comment]
我部署了1.0.0版本，但是注册用户的时候报错如下，protractor.conf.js文件中的baseUrl已经修改为非localhost了，请问下是什么原因呢？

![qq 20180130152821](https://user-images.githubusercontent.com/26590655/35553456-f14ba10a-05d2-11e8-988f-80d1f2fa9453.png)

**Comment by qianmoQ** [comment]
需要修改 web 项目的 proxy配置文件的地址

**Comment by xwinfo** [comment]
proxy.conf.json文件配置为："target": "http://localhost:8080"
我的sever项目的地址是本机的8080端口，这样应该就不需要修改呀

**Comment by qianmoQ** [comment]
是的, 如果是在本地的话, 那么这个是不需要进行代理的, 你这个错误是在1.0.0中的一个 bug, 由于权限的问题导致1.0.0 的部分 API 没有完全释放, 导致有些 api 无法进行未授权访问

**Comment by xwinfo** [comment]
那这个问题有没有解决办法呢？

**Comment by qianmoQ** [comment]
1.1.0 文档已经补齐: http://wiki.ttxit.com/pages/viewpage.action?pageId=14319628 请使用1.1.0 版本进行部署

**Comment by xwinfo** [comment]
非常感谢，我试下1.1.0版本。

**Comment by xwinfo** [comment]
1.1.0版本部署成功，目前发现很多地方图像无法显示
![qq 20180130171442](https://user-images.githubusercontent.com/26590655/35557774-1e347512-05e1-11e8-828b-db4d5d4a5c91.png)
![qq 20180130171326](https://user-images.githubusercontent.com/26590655/35557775-1ecda2e6-05e1-11e8-93ba-59339aab524b.png)
![123](https://user-images.githubusercontent.com/26590655/35557848-591bc5c2-05e1-11e8-820e-358787a96ba5.png)

**Comment by qianmoQ** [comment]
需要设置用户的头像, 目前支持的是一个 url 地址, 设置成功后, 有的浏览器可能需要进行清空缓存

**Comment by qianmoQ** [comment]
其他问题的话, 请新开其他的 issues

**Comment by xwinfo** [comment]
好的，谢谢。
